import torch
from ._constants import BACKUPS_DIR as BACKUPS_DIR, STATE_DICTS_DIR as STATE_DICTS_DIR
from PIL.Image import Image
from _typeshed import Incomplete
from typing import Iterable

def backup_script(src_file_or_dir_path: str, dst_dir: str = ...): ...

class Accumulator:
    data: Incomplete
    def __init__(self, n: int) -> None: ...
    def add(self, *args: list[float]): ...
    def reset(self) -> None: ...

class Animator:
    dynamic_output: Incomplete
    axes: Incomplete
    legend: Incomplete
    fmts: Incomplete
    num_legends: Incomplete
    matrices: Incomplete
    def __init__(self, *, num_axes, num_epochs, ylim, legend, xlabel: str = 'epoch', ylabel: str = 'value', xscale: str = 'linear', yscale: str = 'linear', fmts=('-', '--', '-.', ':'), ax_size=(3.5, 2.5), line_width: int = 1) -> None: ...
    def add(self, ax_num: int, new_epoch: int, new_values: list[float]): ...

def show_images(imgs: Iterable[torch.Tensor | Image], num_rows: int, num_cols: int, titles: Iterable[str] = None, scale: float = 1.5): ...
def save_model_state(model: torch.nn.Module, dir: str = ...): ...
def load_model_state(model: torch.nn.Module, path: str): ...
